import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import NavBar from '../components/NavBar'
import RippleWaveLoader from "../components/mvpblocks/ripple-loader"
import TopNavBar from '@/components/TopNavBar'
import Component from '@/components/comp-586'
import { ThemeProvider } from "@/components/theme-provider"
import GlobalParticles from '@/components/mvpblocks/GlobalParticles';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class" // or "body" if you want to avoid <html> class mismatch
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GlobalParticles />
            <header>
              <Component />
              <NavBar />
              
            </header>
            <RippleWaveLoader />
            {/* Main content */}
            <div style={{ position: 'relative', zIndex: 1 }}>
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}